### ISSUE TITLE
new package suggestion: mmrm

### ISSUE THREAD

**Issue by jpiaskowski** [cran-task-views/MixedModels#21]
from @wviechtb :

> New package just released: https://cran.r-project.org/package=mmrm

>Essentially, it fits models of the form gls(outcome ~ time + other_fixed_effects, correlation = corSymm(form = ~ 1 | subjectid), weights=varIdent(form = ~ 1 | time)) (although one can also use other structures for the error var-cov matrix), so this is what they mean by "marginal linear model without random effects". In one sense, one could regard this as a GEE approach. Alternatively, we could put this under the Specialized models with a new entry Repeated-measures (or something like that).

**Comment by jpiaskowski** [comment]
Would it fit under "convenience wrappers"? It doesn't appear to be introducing new functionality, but it is providing a wrapper for particular circumstances.

**Comment by wviechtb** [comment]
As far as I can tell, it's not just a wrapper around `gls()` (the way I phrased it was a bit misleading), but I didn't dig into the code.

**Comment by jpiaskowski** [comment]
I saw it as a wrapper for TMB, which is great, because that package is hard to use. There are already many packages that handle repeated measures in this TV and other example where specialized covariance are used (e.g. "spatial").  It might make more sense to redefine that as "specialized covariance structure" or something like that for spatial and repeated measures examples.

**Comment by bbolker** [comment]
A little bit more history/context here: I worked a little bit with the lead author of this package (Daniel Sabanes Bove) to try to implement Satterthwaite df computations for glmmTMB. We got somewhere, but we had trouble with the combination of Satterthwaite dfs and "zero-residual-variance" settings (i.e., implementing "R-side" covariance structures, in SAS terminology), so he decided to write this package instead that implements a certain class of models in `TMB`.

**Comment by jpiaskowski** [comment]
I"m in favor of a repeated measures section. We will need to sweep through the entire TV to find all those packages.

**Comment by wviechtb** [comment]
I also think this could be useful, although it is of course a bit tricky since essentially any package for mixed-effects models can handle repeated measures. So we should focus on packages that specifically target this type of application (like `mmrm`).

**Comment by jpiaskowski** [comment]
okay, I'll create a branch and see how it goes.

**Comment by jpiaskowski** [comment]
going to work on this now.

**Comment by jpiaskowski** [comment]
This was added under a new subsection for "specialized models".
