### ISSUE TITLE
migrate kinship-augmented models

### ISSUE THREAD

**Issue by jpiaskowski** [cran-task-views/MixedModels#25]
I need to migrate kinship-augmented models from the Agriculture CTV to this one. Do any maintainers have any pending changes? Please let me know if you have anything that needs to be pushed or if I can proceed.

**Comment by bbolker** [comment]
**tl;dr** go for it.

We didn't discuss/make any decisions about a development workflow. IMO low-tech would be fine: (1) all maintainers are free to push to the main/master branch, (2) for your own convenience, remember to pull before working on stuff, (3) if you're going to work on something for a while then make a branch and merge it when you're done; (4) deal with your own merge conflicts with they arise. I'm not convinced we need anything more elaborate.

**Comment by jpiaskowski** [comment]
For new package additions/removals, I suggest we create issue for them and wait a few days for comments, etc (2 biz days?). I don't think the entire check file needs to be run at every push, but I recommend at least making sure `ctv::ctv2html(ctvFile)` works and the output looks alright before pushing changes.
