### ISSUE TITLE
 Package suggestions: `phylolm` & `sommer`

### ISSUE THREAD

**Issue by Ax3man** [cran-task-views/MixedModels#27]
Thanks so much for adding this task view!

2 possible additions:
1. `phylolm` under "Specialized models: Phylogenetic models"
2. `sommer`, possibly would fit best under "Specialized models: Kinship-augmented models"

**Comment by jpiaskowski** [comment]
-  Sommer has been added (just in the last 30 minutes). 
- [phylom](https://github.com/lamho86/phylolm) might belong in the [phylogenetics task view](https://github.com/cran-task-views/ctv/issues/31) that is currently under construction? @willgearty

**Comment by willgearty** [comment]
Yes, phylolm is included in the phylogenetics tv

**Comment by bbolker** [comment]
Since `phylolm` doesn't do **mixed** models anyway, that's the right place for it. (For now I think I'd like to keep the phylogenetic mixed model packages in this task view, but could be talked into deleting them to avoid redundancy later ...)
