### ISSUE TITLE
add simulation pkgs to power-analysis section?

### ISSUE THREAD

**Issue by bbolker** [cran-task-views/MixedModels#29]
Don't know whether 'simulation' should be lumped with power analysis or a separate sub-head.

Candidates: `faux` (general mixed models), `rxode2`, `mrgsolve` (ODE/pharmacokinetic models), ... ?

**Comment by mattfidler** [comment]
I agree, (add `PKPDsim` for pharmacokinetic/pharmcometric/ode mixed models too)

**Comment by bbolker** [comment]
closed by e2e2c46
