### ISSUE TITLE
Package suggestion: gpboost

### ISSUE THREAD

**Issue by jpiaskowski** [cran-task-views/MixedModels#32]
[gpboost](https://cran.r-project.org/package=gpboost)

> An R package that allows for combining tree-boosting with Gaussian process and mixed effects models. It also allows for independently doing tree-boosting as well as inference and prediction for Gaussian process and mixed effects models. See <https://github.com/fabsig/GPBoost> for more information on the software and Sigrist (2020) <[arXiv:2004.02653](https://arxiv.org/abs/2004.02653)> and Sigrist (2021) <[arXiv:2105.08966](https://arxiv.org/abs/2105.08966)> for more information on the methodology.

**Comment by bbolker** [comment]
closed by e2e2c46
