### ISSUE TITLE
current live version on CRAN has merge conflicts

### ISSUE THREAD

**Issue by palday** [cran-task-views/MixedModels#33]
![image](https://user-images.githubusercontent.com/1677783/197420043-164bbaac-e100-43f4-89ad-785e69b2cc49.png)

![image](https://user-images.githubusercontent.com/1677783/197420058-5307e564-4648-42a9-a0e1-609a1608d2d3.png)

**Comment by bbolker** [comment]
I believe added by 8acc3a9738d4b6815dee0ac2aefbf8d5ff5f75e3, fixed by 05d59dca1b96844e5809151c4814937b71541007 . I forget what the rules are for triggering a re-build of the live version ... ???

**Comment by bbolker** [comment]
Still don't know what the rules are, but the current version is OK.
