### ISSUE TITLE
package suggestion: ggResidpanel

### ISSUE THREAD

**Issue by jpiaskowski** [cran-task-views/MixedModels#34]
https://cran.r-project.org/package=ggResidpanel

automated residual checking - current set to work with lme4/lmerTest and nlme

**Comment by bbolker** [comment]
Hmm. I think I prefer the output of `performance::check_model()` (e.g. this doesn't seem to have a scale-location plot), and `performance` handles a much wider spectrum of (mixed) models (`library(insight); methods("model_info")`). On the other hand I don't want to be too exclusive/opinionated.

**Comment by jpiaskowski** [comment]
This one generates SAS-like graphics - that appears to be the target audience.

**Comment by jpiaskowski** [comment]
Listing package isn't an endorsement, and, we aren't required to list every single relevant package.

**Comment by jpiaskowski** [comment]
addressed in commit 0123f9029036e494bfda742b8a1a47f110262f00
