### ISSUE TITLE
Interesting new package: glmmrBase

### ISSUE THREAD

**Issue by wviechtb** [cran-task-views/MixedModels#39]
Just stumbled across this: https://cran.r-project.org/package=glmmrBase 

"Specification of generalised linear mixed models using the 'R6' object-orientated class system." Could be even considered to fit under 'Basic model fitting'.

**Comment by samuel-watson** [comment]
Suggest closing this issue as I have updated glmmrBase and raised a consolidated issue as #52 with links and resources
