### ISSUE TITLE
submission plan/release-critical tasks?

### ISSUE THREAD

**Issue by bbolker** [cran-task-views/MixedModels#4]
I feel like we should go ahead and pursue something in an [initial proposal format](https://github.com/cran-task-views/ctv/blob/main/Proposal.md) (scope; tentative list of packages; overlap; maintainers) before worrying about finishing/cleaning/polishing, since incorporating suggestions from the task view admins might be extra work if we have done too much development on our own ...

(I'm going to be away/unavailable from now to August 21, but can tackle it when I get back.)

**Comment by jpiaskowski** [comment]
I'd like to keep working on it, even if a submission happens in that time. There's a few patches I want to smooth out and this helps familiarise myself with the content. But even so, agreed, let's proceed on a submission.

**Comment by jpiaskowski** [comment]
Should we start working on this?  The last edit I did to the task view (pending my pull request) was the last major things I think we needed to do to get it in working shape for the CTV committee.

**Comment by jpiaskowski** [comment]
I don't mind drafting a submission, unless you want to. I also wrote up a [check file](https://github.com/cran-task-views/Agriculture/blob/main/check.R) that is useful for performing a few automatic checks (still on CRAN, working URLs) which we could include.

**Comment by bbolker** [comment]
I'm feeling a little bit stuck.  The outline/rubric for the proposal includes a tentative list of packages: "This should encompass the "core" packages and a collection of relevant packages, ideally grouped by sections within the topic."  When I start to write this out I feel like I'm recapitulating our entire proposal.  Maybe we should aggregate the package list to the level-2 headings (basic, specialized, diagnostics and summary stats, data sets, presentation and prediction, inference)?

**Comment by jpiaskowski** [comment]
#### Here's a first stab at the draft proposal

Mixed models are a broad class of statistical models used to analyze data where observations can be assigned *a priori* to discrete groups, and where the parameters describing the differences between groups are treated as random variables. They are also described as multilevel, or hierarchical, models; longitudinal data are often analyzed in this framework.

**Scope:** This proposed task view would includes packages that do general, generalized and nonlinear mixed model fitting (including convenience wrappers), model summary and examination of model diagnostics, inferential tasks (e.g. hypothesis testing, prediction and estimation). Packages for specialized models and cases are included (e.g.  censored data) and data sets that are widely used in teaching and learning about mixed models.  This proposed TV would only include models that incorporate continuous (usually although not always Gaussian) latent variables; this excludes packages that handle hidden Markov Models, finite (discrete) mixture models, latent Markov models, and similar. 

**Packages:** Please see the [draft list](https://github.com/bbolker/mixedmodels-taskview/blob/main/MixedModels.md) of proposed packages for a list of packages to include. The proposed [core packages](https://github.com/bbolker/mixedmodels-taskview/issues/6) currently are: 

- lme4
- nlme
- brms
- MCMCglmm
- multilevelmod
- geepack
- lavaan
- broom.mixed
- DHARMa
- lmerTest
- glmmTMB
- blme
- rstanarm
- ordinal
- robustlmm

**overlap:** There is some overlap with the [Agriculture task](https://cran.r-project.org/web/views/Agriculture.html) view regarding mixed models that include a kinship or relatedness matrix. We could point to that resource or vice versa. There is overlap with the [Robust](https://cran.r-project.org/web/views/Robust.html) which also has a mixed models section, and with the [Bayesian Inference](https://cran.r-project.org/web/views/Bayesian.html) task view.  

**maintainers:** Ben Bolker would be the principal maintainer. Julia Piaskowski (and others) would assist. 

-----------------------------------------------

There's actually more overlap with existing CTVs than I realised, so, it's possible that the CTV committee may not be supportive of this proposal. If so, I do not think this is a wasted effort - it can still be published, just outside of the CTV list. I think my clients would appreciate this very much.

**Comment by bbolker** [comment]
OK, I'm going to go for it. Thanks for getting us unstuck.

**Comment by jpiaskowski** [comment]
Wow, this is really moving along quickly! Would you like me to make formatting changes they requested today?

**Comment by bbolker** [comment]
Making formatting changes would be fine.  I do think I want to make at least one more pass through it before we submit it ...

**Comment by bbolker** [comment]
I think all comments from CTV editors and co-maintainers are addressed.  Does anyone (@jpiaskowski @palday @wviechtb @emitanaka) want to make any further edits before we comment [here](https://github.com/cran-task-views/ctv/issues/35) to turn it back over to CTV editors for onboarding/release?

**Comment by palday** [comment]
I updated the spelling of my name (it is an unusual constellation of L's :slightly_smiling_face:), but I've got nothing more. Let's go! :rocket:

**Comment by emitanaka** [comment]
It looks good to me! Thanks Ben & Julia for the awesome work!

**Comment by jpiaskowski** [comment]
Looks great!

**Comment by jpiaskowski** [comment]
looks good.

**Comment by wviechtb** [comment]
Just pushed a minor update:

- Ending all sentences/bullet points with a period (checked other task views - they do this as well).
- Added Oxford commas (had them already in various places, but now used everywhere for consistency).
- Changed 'residuals' to 'errors' (pedantic, but for example residuals are always correlated; it is the errors that are by default assumed to be uncorrelated but that we can allow to be correlated, for example in lme()).

As far as I am concerned, this is good to go!

**Comment by wviechtb** [comment]
New package just released: https://cran.r-project.org/package=mmrm

Essentially, it fits models of the form `gls(outcome ~ time + other_fixed_effects, correlation = corSymm(form = ~ 1 | subjectid), weights=varIdent(form = ~ 1 | time))` (although one can also use other structures for the error var-cov matrix), so this is what they mean by "marginal linear model without random effects". In one sense, one could regard this as a GEE approach. Alternatively, we could put this under the **Specialized models** with a new entry **Repeated-measures** (or something like that).

**Comment by jpiaskowski** [comment]
I'm going to migrate this new package suggestion to a new issue so we can close this one. (which means we are on our way to a finished CTV!!)
