### ISSUE TITLE
PK stuff arising from last PR

### ISSUE THREAD

**Issue by bbolker** [cran-task-views/MixedModels#43]
add appropriate cross-references to https://cran.r-project.org/view=Pharmacokinetics ! add Matt Fidler as contributor.

**Comment by mattfidler** [comment]
I think that I am already listed as a contributor (though it says Matthew instead of Matt).  Thanks for keeping me in mind, though.

**Comment by bbolker** [comment]
Do you prefer Matt?

**Comment by mattfidler** [comment]
I usually use Matthew for publishing, so this is fine with me.
