### ISSUE TITLE
Package 'BMTME' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/MixedModels#48]
Package [BMTME](https://CRAN.R-project.org/package=BMTME) is currently listed in CRAN Task View [MixedModels](https://CRAN.R-project.org/view=MixedModels) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.  See the section on _CRAN package archivals_ in the [maintenance guidelines](https://github.com/cran-task-views/ctv/blob/main/Maintenance.md) for more details.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by jpiaskowski** [comment]
We removed this from [Agriculture TV](https://github.com/cran-task-views/Agriculture/issues/59) because it does not appear to be maintained at this time.

**Comment by jpiaskowski** [comment]
I recommend removing this given it is still not on CRAN, it is not recently updated and there are several unaddressed issues on the [github repo](https://github.com/frahik/BMTME/issues).

**Comment by bbolker** [comment]
resolved by @jpiaskowski  in 2813961
