### ISSUE TITLE
Package suggestions: `bcmixed` and `boxcoxmix`

### ISSUE THREAD

**Issue by iago-pssjd** [cran-task-views/MixedModels#59]
`bcmixed` and `boxcoxmix` implement Box-Cox transformations for mixed models. Would not they fit mixed models task view?

-  https://cran.r-project.org/web/packages/bcmixed/index.html
- https://cran.r-project.org/web/packages/boxcoxmix/index.html

**Comment by bbolker** [comment]
bac839bd47d345b108
